### ISSUE TITLE
Informative README

### ISSUE THREAD

**Issue by Gbury** [Deducteam/Sukerujo#2]
Currently, the README at the root of the repo is almost a copy of the README of dedukti (save for a few line at the beggining), which makes the projet look like a fork of dedukti, most notably incompatible with a vanilla installation of dedukti since the README still uses the dedukti name and the same binary names as dedukti, together with an install section, all of which strongly suggests that it would overwrite a previous installation of dedukti.

Instead, it would be better to have a different README, maybe explaining what Sukerujo is, the main differences with dedukti, whether is replaces dedukti, what commands/binaries it installs, and how to use it ?

**Comment by rafoo** [comment]
Sukerujo's webpage (http://deducteam.gforge.inria.fr/sukerujo/) is more precise but also a bit obsolete since Sukerujo is not a fork of Dedukti anymore. I think we should merge the README and the webpage.

**Comment by Gbury** [comment]
Indeed, the webpage is bit more informative.
However, it would be better to have a precise description of the new syntax somewhere (or at least an example for each new syntax construction available). As it stands now, the webage tells me that I can use integer and sting notations, but the use of the `builtins.dko` file is not clear: it seems that it is required  for the desugared files to work, but it is in the examples section, which makes it feel more like something that one should write oneself when using sukerujo.
Also, this is a bit off topic, but as I understand it, dedukti lacks a notion of namespace, so it will typically has the same problem of module name collision as `ocaml` as soon as more projects are written for it and used, so is the name `builtins.dk` a good idea ?

**Comment by rafoo** [comment]
OK, note to myself, list of topics to cover:
- literals,
- records,
- let binding

**Comment by rafoo** [comment]
> it would be better to have a precise description of the new syntax

I just updated the webpage to do this (but I did not touch the README yet), is the description precise enough for your need?

**Comment by Gbury** [comment]
The README is indeed a lot clearer now, thanks !
